"""Importadores de formatos externos."""

from yaas.importers.errors import (
    MmanaCompatibilityError,
    MmanaFormatError,
    TouchstoneFormatError,
)
from yaas.importers.mmana import (
    MmanaDocument,
    MmanaEnvironment,
    MmanaLoad,
    MmanaSegmentation,
    MmanaSource,
    MmanaWire,
    detect_mmana_encoding,
    load_mmana,
    parse_mmana,
)
from yaas.importers.mmana_compatibility import (
    MmanaCompatibilityIssue,
    MmanaCompatibilityReport,
    MmanaEnvironmentKind,
    MmanaEnvironmentSemantics,
    MmanaLcqLoad,
    MmanaResistiveLoad,
    MmanaSegmentationSemantics,
    MmanaSegmentOverrideKind,
    MmanaSourceSemantics,
    MmanaWireReference,
    analyze_mmana_compatibility,
    interpret_environment,
    interpret_load,
    interpret_segment_override,
    interpret_segmentation,
    interpret_source,
)
from yaas.importers.touchstone import (
    load_touchstone_s1p,
    parse_touchstone_s1p,
)

__all__ = [
    "MmanaCompatibilityError",
    "MmanaCompatibilityIssue",
    "MmanaCompatibilityReport",
    "MmanaDocument",
    "MmanaEnvironment",
    "MmanaEnvironmentKind",
    "MmanaEnvironmentSemantics",
    "MmanaFormatError",
    "MmanaLcqLoad",
    "MmanaLoad",
    "MmanaResistiveLoad",
    "MmanaSegmentOverrideKind",
    "MmanaSegmentation",
    "MmanaSegmentationSemantics",
    "MmanaSource",
    "MmanaSourceSemantics",
    "MmanaWire",
    "MmanaWireReference",
    "TouchstoneFormatError",
    "analyze_mmana_compatibility",
    "detect_mmana_encoding",
    "interpret_environment",
    "interpret_load",
    "interpret_segment_override",
    "interpret_segmentation",
    "interpret_source",
    "load_mmana",
    "load_touchstone_s1p",
    "parse_mmana",
    "parse_touchstone_s1p",
]