"""Exportación del modelo interno al formato NEC."""

from pathlib import Path

from antsim.domain import SimulationRequest


def _format_number(value: float) -> str:
    """Representa un número de forma compacta para NEC."""
    return f"{value:.12g}"


def simulation_request_to_nec(
    request: SimulationRequest,
    title: str = "Generated by AntSim",
) -> str:
    """Convierte una solicitud de simulación en tarjetas NEC."""
    safe_title = " ".join(title.splitlines()).strip()

    if not safe_title:
        safe_title = "Generated by AntSim"

    lines = [
        f"CM {safe_title}",
        "CE",
    ]

    for wire in request.wires:
        lines.append(
            " ".join(
                [
                    "GW",
                    str(wire.tag),
                    str(wire.segments),
                    _format_number(wire.start.x),
                    _format_number(wire.start.y),
                    _format_number(wire.start.z),
                    _format_number(wire.end.x),
                    _format_number(wire.end.y),
                    _format_number(wire.end.z),
                    _format_number(wire.radius_m),
                ]
            )
        )

    lines.extend(
        [
            "GE 0",
            " ".join(
                [
                    "EX",
                    "0",
                    str(request.source.wire_tag),
                    str(request.source.segment),
                    "0",
                    _format_number(
                        request.source.voltage.real
                    ),
                    _format_number(
                        request.source.voltage.imag
                    ),
                ]
            ),
            " ".join(
                [
                    "FR",
                    "0",
                    "1",
                    "0",
                    "0",
                    _format_number(
                        request.frequency_mhz
                    ),
                    "0",
                ]
            ),
            "EN",
        ]
    )

    return "\n".join(lines) + "\n"


def export_nec(
    request: SimulationRequest,
    destination: str | Path,
    title: str = "Generated by AntSim",
) -> Path:
    """Guarda una solicitud de simulación como archivo NEC."""
    destination_path = Path(destination)

    destination_path.write_text(
        simulation_request_to_nec(
            request=request,
            title=title,
        ),
        encoding="utf-8",
        newline="\n",
    )

    return destination_path