"""Exportación del modelo interno al formato NEC."""

from pathlib import Path

from antsim.domain import (
    SimulationRequest,
    SweepRequest,
    VoltageSource,
    Wire,
)


def _format_number(value: float) -> str:
    """Representa un número de forma compacta para NEC."""
    return f"{value:.12g}"


def _create_nec_text(
    wires: tuple[Wire, ...],
    source: VoltageSource,
    frequency_card: str,
    title: str,
) -> str:
    """Construye las tarjetas NEC comunes."""
    safe_title = " ".join(title.splitlines()).strip()

    if not safe_title:
        safe_title = "Generated by AntSim"

    lines = [
        f"CM {safe_title}",
        "CE",
    ]

    for wire in wires:
        lines.append(
            " ".join(
                [
                    "GW",
                    str(wire.tag),
                    str(wire.segments),
                    _format_number(wire.start.x),
                    _format_number(wire.start.y),
                    _format_number(wire.start.z),
                    _format_number(wire.end.x),
                    _format_number(wire.end.y),
                    _format_number(wire.end.z),
                    _format_number(wire.radius_m),
                ]
            )
        )

    lines.extend(
        [
            "GE 0",
            " ".join(
                [
                    "EX",
                    "0",
                    str(source.wire_tag),
                    str(source.segment),
                    "0",
                    _format_number(source.voltage.real),
                    _format_number(source.voltage.imag),
                ]
            ),
            frequency_card,
            "EN",
        ]
    )

    return "\n".join(lines) + "\n"


def simulation_request_to_nec(
    request: SimulationRequest,
    title: str = "Generated by AntSim",
) -> str:
    """Convierte una simulación de frecuencia única a NEC."""
    frequency_card = " ".join(
        [
            "FR",
            "0",
            "1",
            "0",
            "0",
            _format_number(request.frequency_mhz),
            "0",
        ]
    )

    return _create_nec_text(
        wires=request.wires,
        source=request.source,
        frequency_card=frequency_card,
        title=title,
    )


def sweep_request_to_nec(
    request: SweepRequest,
    title: str = "Generated by AntSim",
) -> str:
    """Convierte un barrido lineal de frecuencias a NEC."""
    frequency_card = " ".join(
        [
            "FR",
            "0",
            str(request.points),
            "0",
            "0",
            _format_number(
                request.start_frequency_mhz
            ),
            _format_number(
                request.frequency_step_mhz
            ),
        ]
    )

    return _create_nec_text(
        wires=request.wires,
        source=request.source,
        frequency_card=frequency_card,
        title=title,
    )


def export_nec(
    request: SimulationRequest,
    destination: str | Path,
    title: str = "Generated by AntSim",
) -> Path:
    """Guarda una simulación de frecuencia única como NEC."""
    destination_path = Path(destination)

    destination_path.write_text(
        simulation_request_to_nec(
            request=request,
            title=title,
        ),
        encoding="utf-8",
        newline="\n",
    )

    return destination_path


def export_sweep_nec(
    request: SweepRequest,
    destination: str | Path,
    title: str = "Generated by AntSim",
) -> Path:
    """Guarda un barrido de frecuencias como archivo NEC."""
    destination_path = Path(destination)

    destination_path.write_text(
        sweep_request_to_nec(
            request=request,
            title=title,
        ),
        encoding="utf-8",
        newline="\n",
    )

    return destination_path