"""Exportación del modelo interno al formato NEC."""

from pathlib import Path

from yaas.domain import (
    AngularSweep,
    Environment,
    FreeSpaceEnvironment,
    PerfectGroundEnvironment,
    RadiationPatternRequest,
    RealGroundEnvironment,
    RealGroundModel,
    SimulationRequest,
    SweepRequest,
    VoltageSource,
    Wire,
)


def _format_number(value: float) -> str:
    """Representa un número de forma compacta para NEC."""
    return f"{value:.12g}"


def _create_nec_text(
    wires: tuple[Wire, ...],
    source: VoltageSource,
    frequency_card: str,
    title: str,
    reference_impedance: float,
    environment: Environment,
    extra_cards: tuple[str, ...] = (),
) -> str:
    """Construye las tarjetas NEC comunes.

    ``extra_cards`` se insertan después de ``frequency_card`` y antes
    de ``EN`` (hoy, solo la tarjeta ``RP`` de un patrón de radiación).
    Con el valor por defecto, la salida es exactamente la histórica.

    El comentario de impedancia de referencia es puramente
    informativo: no es una tarjeta eléctrica ni afecta la simulación.
    NEC2++/4nec2 no leen ``reference_impedance`` de ``SimulationRequest``
    ni de ``SweepRequest``; para que 4nec2 muestre la ROE respecto de
    ese valor, suele haber que configurarlo manualmente en el programa.

    La tarjeta ``GE`` (fin de geometría) siempre precede a ``GN``
    (tipo de tierra), nunca al revés: es el orden ya usado por
    ``PyNecEngine`` y el documentado en
    ``docs/research/nec-ground-configuration.md``. Para
    ``FreeSpaceEnvironment`` se conserva exactamente la salida
    histórica (``GE 0``, sin ninguna tarjeta ``GN``); agregar
    ``GN -1 0 0 0 0 0 0 0`` solo por simetría con ``PyNecEngine``
    cambiaría un archivo ya validado externamente con 4nec2
    (``docs/validation/nec-export-4nec2.md``) sin necesidad.

    La tarjeta ``GN`` de texto tiene siempre **cuatro campos enteros
    (I1-I4) seguidos de seis campos flotantes (F1-F6)** — diez valores
    en total, según la documentación primaria de NEC2 (ver
    ``docs/research/nec-real-ground.md``). Esto es distinto de la
    firma de ``gn_card()`` en PyNEC, que solo recibe ocho argumentos
    posicionales (``ground_type, rad_wire_count, F1..F6``, sin I3/I4,
    reservados/en blanco): no hay que copiar literalmente esa cantidad
    de argumentos al generar la tarjeta de texto. Para tierra real
    (Sommerfeld-Norton) esto ya se validó manualmente con 4nec2 en
    ``docs/validation/real-ground-dipole-4nec2.md``.
    """
    safe_title = " ".join(title.splitlines()).strip()

    if not safe_title:
        safe_title = "Generated by YAAS"

    lines = [
        f"CM {safe_title}",
        (
            "CM Reference impedance: "
            f"{_format_number(reference_impedance)} ohm"
        ),
        (
            "CM Informational only: NEC/4nec2 may require manually "
            "setting this reference impedance to display SWR."
        ),
        "CE",
    ]

    for wire in wires:
        lines.append(
            " ".join(
                [
                    "GW",
                    str(wire.tag),
                    str(wire.segments),
                    _format_number(wire.start.x),
                    _format_number(wire.start.y),
                    _format_number(wire.start.z),
                    _format_number(wire.end.x),
                    _format_number(wire.end.y),
                    _format_number(wire.end.z),
                    _format_number(wire.radius_m),
                ]
            )
        )

    if isinstance(environment, FreeSpaceEnvironment):
        lines.append("GE 0")
    elif isinstance(environment, PerfectGroundEnvironment):
        lines.append("GE 1")
        lines.append("GN 1 0 0 0 0 0 0 0")
    elif isinstance(environment, RealGroundEnvironment):
        if environment.model is not RealGroundModel.SOMMERFELD_NORTON:
            raise ValueError(
                "No se sabe exportar a NEC este RealGroundModel: "
                f"{environment.model!r}."
            )

        lines.append("GE 1")
        lines.append(
            " ".join(
                [
                    "GN",
                    "2", "0", "0", "0",
                    _format_number(environment.relative_permittivity),
                    _format_number(environment.conductivity_s_per_m),
                    "0", "0", "0", "0",
                ]
            )
        )
    else:
        raise ValueError(
            "No se sabe exportar a NEC este tipo de entorno: "
            f"{environment!r}."
        )

    lines.extend(
        [
            " ".join(
                [
                    "EX",
                    "0",
                    str(source.wire_tag),
                    str(source.segment),
                    "0",
                    _format_number(source.voltage.real),
                    _format_number(source.voltage.imag),
                ]
            ),
            frequency_card,
            *extra_cards,
            "EN",
        ]
    )

    return "\n".join(lines) + "\n"


def _single_frequency_card(frequency_mhz: float) -> str:
    """Tarjeta ``FR`` de una única frecuencia."""
    return " ".join(
        [
            "FR",
            "0",
            "1",
            "0",
            "0",
            _format_number(frequency_mhz),
            "0",
        ]
    )


def _radiation_pattern_card(
    theta: AngularSweep,
    phi: AngularSweep,
) -> str:
    """Tarjeta ``RP`` de texto para un patrón de campo lejano.

    La tarjeta tiene diez campos después de ``RP``: cuatro enteros
    (I1-I4) y seis flotantes (F1-F6). I4 es el campo ``XNDA`` completo,
    escrito como un único token de cuatro dígitos: ``0000`` (salida de
    ejes mayor/menor, sin normalización, ganancia de potencia, sin
    promedio). Esto es distinto de ``PyNEC.rp_card()``, que recibe
    trece argumentos porque separa ``XNDA`` en cuatro enteros: no hay
    que copiar esa firma a la tarjeta de texto.
    """
    return " ".join(
        [
            "RP",
            "0",  # I1: modo normal (onda espacial)
            str(theta.count),  # I2: cantidad de ángulos theta
            str(phi.count),  # I3: cantidad de ángulos phi
            "0000",  # I4: XNDA
            _format_number(theta.start_deg),  # F1
            _format_number(phi.start_deg),  # F2
            _format_number(theta.step_deg),  # F3
            _format_number(phi.step_deg),  # F4
            _format_number(0.0),  # F5: sin distancia radial
            _format_number(0.0),  # F6: sin normalización de ganancia
        ]
    )


def simulation_request_to_nec(
    request: SimulationRequest,
    title: str = "Generated by YAAS",
) -> str:
    """Convierte una simulación de frecuencia única a NEC."""
    return _create_nec_text(
        wires=request.wires,
        source=request.source,
        frequency_card=_single_frequency_card(request.frequency_mhz),
        title=title,
        reference_impedance=request.reference_impedance,
        environment=request.environment,
    )


def radiation_pattern_request_to_nec(
    request: RadiationPatternRequest,
    title: str = "Generated by YAAS",
    reference_impedance: float = 50.0,
) -> str:
    """Convierte un patrón de radiación de frecuencia única a NEC.

    Genera exactamente las mismas tarjetas ``CM``/``CE``/``GW``/``GE``/
    ``GN``/``EX``/``FR`` que ``simulation_request_to_nec`` para la
    misma geometría, entorno, fuente y frecuencia, más una única
    tarjeta ``RP`` después de ``FR`` y antes de ``EN``. Ese es el orden
    textual portable elegido por este exportador (el mismo de los
    archivos ya validados con 4nec2), no el orden interno de llamadas
    de la API de PyNEC. No se agrega ``XQ``: la tarjeta ``RP`` ya inicia
    la ejecución.

    ``RadiationPatternRequest`` no tiene impedancia de referencia; la
    de ``reference_impedance`` solo aparece en el comentario
    informativo ``CM``, igual que en la exportación puntual.
    """
    if not isinstance(request, RadiationPatternRequest):
        raise TypeError(
            "Se esperaba un RadiationPatternRequest: "
            f"{type(request).__name__!r}."
        )

    # Reutiliza las validaciones y la salida de la exportación puntual
    # equivalente, incluida la impedancia de referencia.
    point_request = SimulationRequest(
        frequency_mhz=request.frequency_mhz,
        wires=request.wires,
        source=request.source,
        reference_impedance=reference_impedance,
        environment=request.environment,
    )

    return _create_nec_text(
        wires=point_request.wires,
        source=point_request.source,
        frequency_card=_single_frequency_card(point_request.frequency_mhz),
        title=title,
        reference_impedance=point_request.reference_impedance,
        environment=point_request.environment,
        extra_cards=(
            _radiation_pattern_card(request.theta, request.phi),
        ),
    )


def sweep_request_to_nec(
    request: SweepRequest,
    title: str = "Generated by YAAS",
) -> str:
    """Convierte un barrido lineal de frecuencias a NEC."""
    frequency_card = " ".join(
        [
            "FR",
            "0",
            str(request.points),
            "0",
            "0",
            _format_number(
                request.start_frequency_mhz
            ),
            _format_number(
                request.frequency_step_mhz
            ),
        ]
    )

    return _create_nec_text(
        wires=request.wires,
        source=request.source,
        frequency_card=frequency_card,
        title=title,
        reference_impedance=request.reference_impedance,
        environment=request.environment,
    )


def export_nec(
    request: SimulationRequest,
    destination: str | Path,
    title: str = "Generated by YAAS",
) -> Path:
    """Guarda una simulación de frecuencia única como NEC."""
    destination_path = Path(destination)

    destination_path.write_text(
        simulation_request_to_nec(
            request=request,
            title=title,
        ),
        encoding="utf-8",
        newline="\n",
    )

    return destination_path


def export_radiation_pattern_nec(
    request: RadiationPatternRequest,
    destination: str | Path,
    title: str = "Generated by YAAS",
    reference_impedance: float = 50.0,
) -> Path:
    """Guarda un patrón de radiación de frecuencia única como NEC.

    El texto se genera antes de abrir el archivo, así que una
    solicitud inválida no crea ni modifica ningún archivo.
    """
    content = radiation_pattern_request_to_nec(
        request=request,
        title=title,
        reference_impedance=reference_impedance,
    )
    destination_path = Path(destination)

    destination_path.write_text(
        content,
        encoding="utf-8",
        newline="\n",
    )

    return destination_path


def export_sweep_nec(
    request: SweepRequest,
    destination: str | Path,
    title: str = "Generated by YAAS",
) -> Path:
    """Guarda un barrido de frecuencias como archivo NEC."""
    destination_path = Path(destination)

    destination_path.write_text(
        sweep_request_to_nec(
            request=request,
            title=title,
        ),
        encoding="utf-8",
        newline="\n",
    )

    return destination_path