"""Exportación del modelo interno al formato NEC."""

from pathlib import Path

from yaas.domain import (
    Environment,
    FreeSpaceEnvironment,
    PerfectGroundEnvironment,
    RealGroundEnvironment,
    RealGroundModel,
    SimulationRequest,
    SweepRequest,
    VoltageSource,
    Wire,
)


def _format_number(value: float) -> str:
    """Representa un número de forma compacta para NEC."""
    return f"{value:.12g}"


def _create_nec_text(
    wires: tuple[Wire, ...],
    source: VoltageSource,
    frequency_card: str,
    title: str,
    reference_impedance: float,
    environment: Environment,
) -> str:
    """Construye las tarjetas NEC comunes.

    El comentario de impedancia de referencia es puramente
    informativo: no es una tarjeta eléctrica ni afecta la simulación.
    NEC2++/4nec2 no leen ``reference_impedance`` de ``SimulationRequest``
    ni de ``SweepRequest``; para que 4nec2 muestre la ROE respecto de
    ese valor, suele haber que configurarlo manualmente en el programa.

    La tarjeta ``GE`` (fin de geometría) siempre precede a ``GN``
    (tipo de tierra), nunca al revés: es el orden ya usado por
    ``PyNecEngine`` y el documentado en
    ``docs/research/nec-ground-configuration.md``. Para
    ``FreeSpaceEnvironment`` se conserva exactamente la salida
    histórica (``GE 0``, sin ninguna tarjeta ``GN``); agregar
    ``GN -1 0 0 0 0 0 0 0`` solo por simetría con ``PyNecEngine``
    cambiaría un archivo ya validado externamente con 4nec2
    (``docs/validation/nec-export-4nec2.md``) sin necesidad.

    La tarjeta ``GN`` de texto tiene siempre **cuatro campos enteros
    (I1-I4) seguidos de seis campos flotantes (F1-F6)** — diez valores
    en total, según la documentación primaria de NEC2 (ver
    ``docs/research/nec-real-ground.md``). Esto es distinto de la
    firma de ``gn_card()`` en PyNEC, que solo recibe ocho argumentos
    posicionales (``ground_type, rad_wire_count, F1..F6``, sin I3/I4,
    reservados/en blanco): no hay que copiar literalmente esa cantidad
    de argumentos al generar la tarjeta de texto. Para tierra real
    (Sommerfeld-Norton) esto ya se validó manualmente con 4nec2 en
    ``docs/validation/real-ground-dipole-4nec2.md``.
    """
    safe_title = " ".join(title.splitlines()).strip()

    if not safe_title:
        safe_title = "Generated by YAAS"

    lines = [
        f"CM {safe_title}",
        (
            "CM Reference impedance: "
            f"{_format_number(reference_impedance)} ohm"
        ),
        (
            "CM Informational only: NEC/4nec2 may require manually "
            "setting this reference impedance to display SWR."
        ),
        "CE",
    ]

    for wire in wires:
        lines.append(
            " ".join(
                [
                    "GW",
                    str(wire.tag),
                    str(wire.segments),
                    _format_number(wire.start.x),
                    _format_number(wire.start.y),
                    _format_number(wire.start.z),
                    _format_number(wire.end.x),
                    _format_number(wire.end.y),
                    _format_number(wire.end.z),
                    _format_number(wire.radius_m),
                ]
            )
        )

    if isinstance(environment, FreeSpaceEnvironment):
        lines.append("GE 0")
    elif isinstance(environment, PerfectGroundEnvironment):
        lines.append("GE 1")
        lines.append("GN 1 0 0 0 0 0 0 0")
    elif isinstance(environment, RealGroundEnvironment):
        if environment.model is not RealGroundModel.SOMMERFELD_NORTON:
            raise ValueError(
                "No se sabe exportar a NEC este RealGroundModel: "
                f"{environment.model!r}."
            )

        lines.append("GE 1")
        lines.append(
            " ".join(
                [
                    "GN",
                    "2", "0", "0", "0",
                    _format_number(environment.relative_permittivity),
                    _format_number(environment.conductivity_s_per_m),
                    "0", "0", "0", "0",
                ]
            )
        )
    else:
        raise ValueError(
            "No se sabe exportar a NEC este tipo de entorno: "
            f"{environment!r}."
        )

    lines.extend(
        [
            " ".join(
                [
                    "EX",
                    "0",
                    str(source.wire_tag),
                    str(source.segment),
                    "0",
                    _format_number(source.voltage.real),
                    _format_number(source.voltage.imag),
                ]
            ),
            frequency_card,
            "EN",
        ]
    )

    return "\n".join(lines) + "\n"


def simulation_request_to_nec(
    request: SimulationRequest,
    title: str = "Generated by YAAS",
) -> str:
    """Convierte una simulación de frecuencia única a NEC."""
    frequency_card = " ".join(
        [
            "FR",
            "0",
            "1",
            "0",
            "0",
            _format_number(request.frequency_mhz),
            "0",
        ]
    )

    return _create_nec_text(
        wires=request.wires,
        source=request.source,
        frequency_card=frequency_card,
        title=title,
        reference_impedance=request.reference_impedance,
        environment=request.environment,
    )


def sweep_request_to_nec(
    request: SweepRequest,
    title: str = "Generated by YAAS",
) -> str:
    """Convierte un barrido lineal de frecuencias a NEC."""
    frequency_card = " ".join(
        [
            "FR",
            "0",
            str(request.points),
            "0",
            "0",
            _format_number(
                request.start_frequency_mhz
            ),
            _format_number(
                request.frequency_step_mhz
            ),
        ]
    )

    return _create_nec_text(
        wires=request.wires,
        source=request.source,
        frequency_card=frequency_card,
        title=title,
        reference_impedance=request.reference_impedance,
        environment=request.environment,
    )


def export_nec(
    request: SimulationRequest,
    destination: str | Path,
    title: str = "Generated by YAAS",
) -> Path:
    """Guarda una simulación de frecuencia única como NEC."""
    destination_path = Path(destination)

    destination_path.write_text(
        simulation_request_to_nec(
            request=request,
            title=title,
        ),
        encoding="utf-8",
        newline="\n",
    )

    return destination_path


def export_sweep_nec(
    request: SweepRequest,
    destination: str | Path,
    title: str = "Generated by YAAS",
) -> Path:
    """Guarda un barrido de frecuencias como archivo NEC."""
    destination_path = Path(destination)

    destination_path.write_text(
        sweep_request_to_nec(
            request=request,
            title=title,
        ),
        encoding="utf-8",
        newline="\n",
    )

    return destination_path